# Generated by Django 4.2.7 on 2026-07-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
