# Generated by Django 4.2.7 on 2026-07-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorapi', '0002_donor_college_donor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
    ]
